### ISSUE TITLE
漫画

### ISSUE THREAD

**Issue by Nachogao** [soruly/anilist-chinese#111]
能否添加漫画的翻译，我这边在试一试。

**Comment by soruly** [comment]
因為我自己很少看漫畫, 所以沒有處理漫畫類別的翻譯, 抱歉🙇🏻‍♂️

**Comment by Nachogao** [comment]
我试了一下，动画和漫画的Id是不重复的，所以只需要在代码中添加

`if (window.location.pathname.indexOf("/manga/") === 0) {
        translate();
      }`，

在`if (window.location.pathname.indexOf("/anime/") === 0) {
        translate();
      }`
下面就可以了

**Comment by soruly** [comment]
但是資料庫配對標題使用的是 anime ID, 如果要翻譯漫畫標題的話, 要人手把現有的 5892 個 anime ID 配對成 manga ID
